name: ESP32-S3 CI  🚀

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # 2. Build proyek menggunakan espressif/esp-idf-ci-action
    - name: Build ESP32-S3 Project
      uses: espressif/esp-idf-ci-action@v1
      with:
        target: esp32s3
        esp_idf_version: v5.5.1
        path: ./
        command: |
          idf.py build

    # 3. Upload hanya file binary yang diperlukan
    - name: Archive specific build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32s3-essential-binaries-v5.5.1
        path: |
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/led_wifi.bin
        if-no-files-found: error
        retention-days: 5
